### ISSUE TITLE
Include RSS feed

### ISSUE THREAD

**Issue by darekkay** [prateek3255/blog#21]
Hey Prateek, 
I'd like to subscribe to your blog using RSS (I'm not a newsletter person). Do you mind adding the [11ty RSS plugin](https://www.11ty.dev/docs/plugins/rss/) to your blog?

Keep up the good content :+1:

**Comment by prateek3255** [comment]
Hey, @darekkay thanks for bringing this to notice. 🙌🏼  

I have added the RSS feed here - https://prateeksurana.me/blog/feed.xml using the plugin you mentioned.
